// AngularDevise
// -------------------
// v1.0.0
//
// Copyright (c)2014 Justin Ridgewell
// Distributed under MIT license
//
// https://github.com/cloudspace/angular_devise

!function(a){"use strict";var b=a.module("Devise",[]);b.factory("deviseInterceptor401",["$rootScope","$q",function(a,b){return{responseError:function(c){if(401===c.status&&c.config.interceptAuth){var d=b.defer();return a.$broadcast("devise:unauthorized",c,d),d.promise}return b.reject(c)}}}]).config(["$httpProvider",function(a){a.interceptors.push("deviseInterceptor401")}]),b.provider("Auth",function(){function b(a,b){var c={method:f[a].toLowerCase(),url:e[a],interceptAuth:g};return b&&(h?(c.data={},c.data[h]=b):c.data=b),c}function c(b,c){a.forEach(b,function(a,d){this[d+c]=function(a){return void 0===a?b[d]:(b[d]=a,this)}},this)}function d(a){return function(){return a}}var e={login:"/users/sign_in.json",logout:"/users/sign_out.json",register:"/users.json"},f={login:"POST",logout:"DELETE",register:"POST"},g=!1,h="user",i=function(a){return a.data};c.call(this,f,"Method"),c.call(this,e,"Path"),this.interceptAuth=function(a){return void 0===a?g:(g=!!a,this)},this.resourceName=function(a){return void 0===a?h:(h=a,this)},this.parse=function(a){return"function"!=typeof a?i:(i=a,this)},this.$get=["$q","$http","$rootScope",function(a,c,e){function f(a){return j._currentUser=a,a}function g(){f(null)}function h(a){return function(b){return e.$broadcast("devise:"+a,b),b}}var j={_currentUser:null,parse:i,login:function(a){var d=arguments.length>0,e=j.isAuthenticated();return a=a||{},c(b("login",a)).then(j.parse).then(f).then(function(a){return d&&!e?h("new-session")(a):a}).then(h("login"))},logout:function(){var a=d(j._currentUser);return c(b("logout")).then(g).then(a).then(h("logout"))},register:function(a){return a=a||{},c(b("register",a)).then(j.parse).then(f).then(h("new-registration"))},currentUser:function(){return j.isAuthenticated()?a.when(j._currentUser):j.login()},isAuthenticated:function(){return!!j._currentUser}};return j}]})}(angular);